# Generated by Django 5.0.4 on 2024-05-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='teamname',
        ),
        migrations.AddField(
            model_name='post',
            name='Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
