# Generated by Django 5.0.4 on 2024-05-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Score',
            new_name='score',
        ),
    ]
