export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";
export const GET_USERS_BY_ROLE_SUCCESS = "GET_USERS_BY_ROLE_SUCCESS";
export const GET_USERS_BY_ROLE_FAILURE = "GET_USERS_BY_ROLE_FAILURE";
export const GET_USERNAME = "GET_USERNAME";
export const GET_USERNAME_FAILURE = "GET_USERNAME";
