# Generated by Django 5.0.4 on 2024-08-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoreboardentry',
            options={},
        ),
        migrations.AlterField(
            model_name='scoreboardentry',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scoreboardentry',
            name='score',
            field=models.IntegerField(),
        ),
    ]
