# Generated by Django 4.2.15 on 2024-09-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_alter_scoreboardentry_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreboardentry',
            name='user',
        ),
    ]
