# Generated by Django 4.2.15 on 2024-09-02 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoreboard', '0003_remove_scoreboardentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboardentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
